m	ain: tcpechoserver1.c tcpechoserver2.c tcpechoclient.c
	gcc -pthread -Wall -o tcpechoserver1.out tcpechoserver1.c
	gcc -Wall -o tcpechoserver2.out tcpechoserver2.c
	gcc -Wall -o tcpechoclient.out tcpechoclient.c
clean:
	rm *.out

